name: Build
on:
  workflow_dispatch:
  pull_request:

jobs:
  typecheck:
    name: Typecheck & Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # ratchet:actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - name: Installer npm-avhengigheter
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npm ci
      - name: Kjør ESLint
        run: npm run lint
      - name: Kjør typecheck
        run: npm run typecheck

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # ratchet:actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - name: Installer npm-avhengigheter
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npm ci
      - name: Bygg applikasjon
        run: |
          npm run build
          npm run build:server
