name: Deploy til dev
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"
  actions: "read"

jobs:
  build:
    name: Bygg og push Docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # ratchet:actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - name: Installer npm-avhengigheter
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npm ci
      - name: Kj√∏r ESLint
        run: npm run lint
      - name: Bygg applikasjon
        run: |
          npm run build
          npm run build:server
      - uses: nais/docker-build-push@87f920b0411b987d9a1fd4113aa384e1e3b54f2c # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: etterlatte
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy:
    name: Deploy til dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v4
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}
