name: Deploy til dev
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"
  actions: "read"

jobs:
  build:
    name: Bygg og push Docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # ratchet:actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - name: Installer npm-avhengigheter
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npm ci
      - name: Kj√∏r ESLint
        run: npm run lint
      - name: Bygg applikasjon
        run: |
          npm run build
          npm run build:server
      - uses: nais/docker-build-push@791ebb6f74b82849c742a9bc9c97abe44c6c111f # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: etterlatte
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy:
    name: Deploy til dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # ratchet:actions/checkout@v4
      - uses: nais/deploy/actions/deploy@961addd1e4d4211f1a7333ada5fde85f7c9aa5b7 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}
